# Generated by Django 5.2.4 on 2025-07-31 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='期刊名称')),
                ('impact_factor', models.FloatField(blank=True, null=True, verbose_name='影响因子')),
                ('cas_partition', models.CharField(blank=True, max_length=50, null=True, verbose_name='中科院分区')),
                ('jcr_partition', models.CharField(blank=True, max_length=50, null=True, verbose_name='JCR分区')),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('authors', models.TextField(help_text='多个作者用逗号分隔', verbose_name='作者')),
                ('pub_year', models.IntegerField(verbose_name='发表年份')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='发表日期')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='卷号')),
                ('issue', models.CharField(blank=True, max_length=50, null=True, verbose_name='期号')),
                ('pages', models.CharField(blank=True, max_length=50, null=True, verbose_name='页码')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='DOI')),
                ('pmid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='PMID')),
                ('keywords', models.TextField(blank=True, help_text='多个关键词用分号分隔', null=True, verbose_name='关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literature.journal', verbose_name='期刊')),
            ],
        ),
        migrations.CreateModel(
            name='LiteratureUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, help_text='1-5星', null=True, verbose_name='评级')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literature.literature', verbose_name='文献')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'unique_together': {('user', 'literature')},
            },
        ),
    ]
