# Generated by Django 5.2.4 on 2025-08-02 12:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperationapplication',
            options={'ordering': ['-created_at'], 'verbose_name': '合作申请', 'verbose_name_plural': '合作申请'},
        ),
        migrations.AlterModelOptions(
            name='cooperationpost',
            options={'ordering': ['-created_at'], 'verbose_name': '合作帖子', 'verbose_name_plural': '合作帖子'},
        ),
        migrations.AlterModelOptions(
            name='cooperationprogress',
            options={'ordering': ['-created_at'], 'verbose_name': '合作进度', 'verbose_name_plural': '合作进度'},
        ),
        migrations.AlterModelOptions(
            name='cooperationreview',
            options={'ordering': ['-created_at'], 'verbose_name': '合作评价', 'verbose_name_plural': '合作评价'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': '技能', 'verbose_name_plural': '技能'},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'verbose_name': '用户技能', 'verbose_name_plural': '用户技能'},
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请者'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='available_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='可开始日期'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='cover_letter',
            field=models.TextField(help_text='申请说明', verbose_name='申请信'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, help_text='预计完成时间（小时）', null=True, verbose_name='预计时长'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='作品集链接', null=True, verbose_name='作品集链接'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='cooperation.cooperationpost', verbose_name='合作帖子'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='报价'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='proposed_solution',
            field=models.TextField(help_text='解决方案', verbose_name='解决方案'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='relevant_experience',
            field=models.TextField(blank=True, help_text='相关经验', null=True, verbose_name='相关经验'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='review_note',
            field=models.TextField(blank=True, null=True, verbose_name='审核备注'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='cooperationapplication',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='application_count',
            field=models.PositiveIntegerField(default=0, verbose_name='申请次数'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预算'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='cooperation_type',
            field=models.CharField(choices=[('mutual', '互助'), ('collab', '合作')], max_length=10, verbose_name='合作类型'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('expert', '专家')], default='intermediate', max_length=20, verbose_name='难度级别'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='expected_duration',
            field=models.PositiveIntegerField(blank=True, help_text='预期完成时间（小时）', null=True, verbose_name='预期时长'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation_posts', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='required_skills',
            field=models.JSONField(default=list, help_text='所需技能列表', verbose_name='所需技能'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='requirements',
            field=models.JSONField(default=dict, help_text='结构化需求描述', verbose_name='需求详情'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='reward_description',
            field=models.TextField(help_text='酬劳或合作条件', verbose_name='酬劳描述'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='status',
            field=models.CharField(choices=[('pending', '待接单'), ('progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='tags',
            field=models.JSONField(default=list, help_text='项目标签', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='cooperationpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='cooperationprogress',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='合作者'),
        ),
        migrations.AlterField(
            model_name='cooperationprogress',
            name='cooperation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='cooperation.cooperationpost', verbose_name='合作项目'),
        ),
        migrations.AlterField(
            model_name='cooperationprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cooperationprogress',
            name='deliverables',
            field=models.JSONField(default=list, help_text='交付文件列表', verbose_name='交付物'),
        ),
        migrations.AlterField(
            model_name='cooperationprogress',
            name='description',
            field=models.TextField(verbose_name='进度描述'),
        ),
        migrations.AlterField(
            model_name='cooperationprogress',
            name='progress_percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='进度百分比'),
        ),
        migrations.AlterField(
            model_name='cooperationreview',
            name='comment',
            field=models.TextField(verbose_name='评价内容'),
        ),
        migrations.AlterField(
            model_name='cooperationreview',
            name='communication_rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='沟通评分'),
        ),
        migrations.AlterField(
            model_name='cooperationreview',
            name='cooperation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='cooperation.cooperationpost', verbose_name='合作项目'),
        ),
        migrations.AlterField(
            model_name='cooperationreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cooperationreview',
            name='quality_rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='质量评分'),
        ),
        migrations.AlterField(
            model_name='cooperationreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='cooperationreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评价者'),
        ),
        migrations.AlterField(
            model_name='cooperationreview',
            name='timeliness_rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='及时性评分'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(max_length=50, verbose_name='技能分类'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='技能名称'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='proficiency_level',
            field=models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('expert', '专家')], default='beginner', max_length=20, verbose_name='熟练度'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperation.skill', verbose_name='技能'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='已认证'),
        ),
    ]
