# Generated by Django 5.2.4 on 2025-08-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_at_user_is_verified_user_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointsRecord',
        ),
    ]
