# Generated by Django 5.2.4 on 2025-08-03 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_pointsrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('authors', models.TextField(verbose_name='作者')),
                ('abstract', models.TextField(blank=True, verbose_name='摘要')),
                ('keywords', models.TextField(blank=True, verbose_name='关键词')),
                ('doi', models.CharField(blank=True, max_length=255, verbose_name='DOI')),
                ('url', models.URLField(blank=True, verbose_name='链接')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='发表日期')),
                ('journal', models.CharField(blank=True, max_length=255, verbose_name='期刊')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='卷')),
                ('issue', models.CharField(blank=True, max_length=50, verbose_name='期')),
                ('pages', models.CharField(blank=True, max_length=50, verbose_name='页码')),
                ('category', models.CharField(max_length=100, verbose_name='领域分类')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='literatures/', verbose_name='文件路径')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literatures', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
